from .utils import RangeDict
from . import mids


common_sids = RangeDict({
    151: 'System Diagnostic Code #1',
    152: 'System Diagnostic Code #2',
    153: 'System Diagnostic Code #3',
    154: 'System Diagnostic Code #4',
    155: 'System Diagnostic Code #5',
    range(156, 202): 'Reserved',
    203: 'Door Switch',
    204: 'Diagnostics Data Available Through Alternate Reporting Method',
    205: 'J1939 Network #3',
    206: 'J1939 Network #2',
    207: 'Battery #1 Temperature',
    208: 'Battery #2 Temperature',
    209: 'Start Enable Device #2',
    210: 'Oil Temperature Sensor',
    211: 'Sensor Supply Voltage #2 (+5V DC)',
    212: 'Sensor Supply Voltage #1 (+5V DC)',
    213: 'PLC Data Link',
    214: 'ECU Backup Battery',
    215: 'Cab Interior Temperature Thermostat',
    216: 'Other ECUs Have Reported Fault Codes Affecting Operation',
    217: 'Anti-theft Start Inhibit (Password Valid Indicator)',
    218: 'ECM Main Relay',
    219: 'Start Signal Indicator',
    220: 'Electronic Tractor/Trailer Interface (ISO 11992)',
    221: 'Internal Sensor Voltage Supply',
    222: 'Protect Lamp',
    223: 'Ambient Light Sensor',
    224: 'Audible Alarm',
    225: 'Green Lamp',
    226: 'Transmission Neutral Switch',
    227: 'Auxiliary Analog Input #1',
    228: 'High Side Refrigerant Pressure Switch',
    229: 'Kickdown Switch',
    230: 'Idle Validation Switch',
    231: 'SAE J1939 Data Link',
    232: '5 Volts DC Supply',
    233: 'Controller #2',
    234: 'Parking Brake On Actuator',
    235: 'Parking Brake Off Actuator',
    236: 'Power Connect Device',
    237: 'Start Enable Device',
    238: 'Diagnostic Lamp—Red',
    239: 'Diagnostic Light—Amber',
    240: 'Program Memory',
    241: 'Set aside for Systems Diagnostics',
    242: 'Cruise Control Resume Switch',
    243: 'Cruise Control Set Switch',
    244: 'Cruise Control Enable Switch',
    245: 'Clutch Pedal Switch #1',
    246: 'Brake Pedal Switch #1',
    247: 'Brake Pedal Switch #2',
    248: 'Proprietary Data Link',
    249: 'SAE J1922 Data Link',
    250: 'SAE J1708 (SAE J1587) Data Link',
    251: 'Power Supply',
    252: 'Calibration Module',
    253: 'Calibration Memory',
    254: 'Controller #1',
    255: 'Reserved',
})


# Engine SIDs (MID = 128, 175, 183, 184, 185, 186)
engine_sids = RangeDict({
    0: 'Reserved',
    1: 'Injector Cylinder #1',
    2: 'Injector Cylinder #2',
    3: 'Injector Cylinder #3',
    4: 'Injector Cylinder #4',
    5: 'Injector Cylinder #5',
    6: 'Injector Cylinder #6',
    7: 'Injector Cylinder #7',
    8: 'Injector Cylinder #8',
    9: 'Injector Cylinder #9',
    10: 'Injector Cylinder #10',
    11: 'Injector Cylinder #11',
    12: 'Injector Cylinder #12',
    13: 'Injector Cylinder #13',
    14: 'Injector Cylinder #14',
    15: 'Injector Cylinder #15',
    16: 'Injector Cylinder #16',
    17: 'Fuel Shutoff Valve #1',
    18: 'Fuel Control Valve',
    19: 'Throttle Bypass Valve',
    20: 'Timing Actuator',
    21: 'Engine Position Sensor',
    22: 'Timing Sensor',
    23: 'Rack Actuator',
    24: 'Rack Position Sensor',
    25: 'External Engine Protection Input #1',
    26: 'Auxiliary Output Device Driver #1',
    27: 'Variable Geometry Turbocharger Actuator #1',
    28: 'Variable Geometry Turbocharger Actuator #2',
    29: 'External Fuel Command Input',
    30: 'External Speed Command Input',
    31: 'Tachometer Signal Output',
    32: 'Turbocharger #1 Wastegate Drive',
    33: 'Fan Clutch Output Device Driver',
    34: 'Exhaust Back Pressure Sensor',
    35: 'Exhaust Back Pressure Regulator Solenoid',
    36: 'Glow Plug Lamp',
    37: 'Electronic Drive Unit Power Relay',
    38: 'Glow Plug Relay',
    39: 'Engine Starter Motor Relay',
    40: 'Auxiliary Output Device Driver #2',
    41: 'ECM 8 Volts DC Supply',
    42: 'Injection Control Pressure Regulator',
    43: 'Autoshift High Gear Actuator',
    44: 'Autoshift Low Gear Actuator',
    45: 'Autoshift Neutral Actuator',
    46: 'Autoshift Common Low Side (Return)',
    47: 'Injector Cylinder #17',
    48: 'Injector Cylinder #18',
    49: 'Injector Cylinder #19',
    50: 'Injector Cylinder #20',
    51: 'Auxiliary Output Device Driver #3',
    52: 'Auxiliary Output Device Driver #4',
    53: 'Auxiliary Output Device Driver #5',
    54: 'Auxiliary Output Device Driver #6',
    55: 'Auxiliary Output Device Driver #7',
    56: 'Auxiliary Output Device Driver #8',
    57: 'Auxiliary PWM Driver #1',
    58: 'Auxiliary PWM Driver #2',
    59: 'Auxiliary PWM Driver #3',
    60: 'Auxiliary PWM Driver #4',
    61: 'Variable Swirl System Valve',
    62: 'Prestroke Sensor',
    63: 'Prestroke Actuator',
    64: 'Engine Speed Sensor #2',
    65: 'Heated Oxygen Sensor',
    66: 'Ignition Control Mode Signal',
    67: 'Ignition Control Timing Signal',
    68: 'Secondary Turbo Inlet Pressure',
    69: 'After Cooler-Oil Cooler Coolant Temperature',
    70: 'Inlet Air Heater Driver #1',
    71: 'Inlet Air Heater Driver #2',
    72: 'Injector Cylinder #21',
    73: 'Injector Cylinder #22',
    74: 'Injector Cylinder #23',
    75: 'Injector Cylinder #24',
    76: 'Knock Sensor',
    77: 'Gas Metering Valve',
    78: 'Fuel Supply Pump Actuator',
    79: 'Engine (Compression) Brake Output #1',
    80: 'Engine (Compression) Brake Output #2',
    81: 'Engine (Exhaust) Brake Output',
    82: 'Engine (Compression) Brake Output #3',
    83: 'Fuel Control Valve #2',
    84: 'Timing Actuator #2',
    85: 'Engine Oil Burn Valve',
    86: 'Engine Oil Replacement Valve',
    87: 'Idle Shutdown Vehicle Accessories Relay Driver',
    88: 'Turbocharger #2 Wastegate Drive',
    89: 'Air Compressor Actuator Circuit',
    90: 'Engine Cylinder #1 Knock Sensor',
    91: 'Engine Cylinder #2 Knock Sensor',
    92: 'Engine Cylinder #3 Knock Sensor',
    93: 'Engine Cylinder #4 Knock Sensor',
    94: 'Engine Cylinder #5 Knock Sensor',
    95: 'Engine Cylinder #6 Knock Sensor',
    96: 'Engine Cylinder #7 Knock Sensor',
    97: 'Engine Cylinder #8 Knock Sensor',
    98: 'Engine Cylinder #9 Knock Sensor',
    99: 'Engine Cylinder #10 Knock Sensor',
    100: 'Engine Cylinder #11 Knock Sensor',
    101: 'Engine Cylinder #12 Knock Sensor',
    102: 'Engine Cylinder #13 Knock Sensor',
    103: 'Engine Cylinder #14 Knock Sensor',
    104: 'Engine Cylinder #15 Knock Sensor',
    105: 'Engine Cylinder #16 Knock Sensor',
    106: 'Engine Cylinder #17 Knock Sensor',
    107: 'Engine Cylinder #18 Knock Sensor',
    108: 'Engine Cylinder #19 Knock Sensor',
    109: 'Engine Cylinder #20 Knock Sensor',
    110: 'Engine Cylinder #21 Knock Sensor',
    111: 'Engine Cylinder #22 Knock Sensor',
    112: 'Engine Cylinder #23 Knock Sensor',
    113: 'Engine Cylinder #24 Knock Sensor',
    114: 'Multiple Unit Synchronization Switch',
    115: 'Engine Oil Change Interval',
    116: 'Engine was Shut Down Hot',
    117: 'Engine has been Shut Down from Data Link Information',
    118: 'Injector Needle Lift Sensor #1',
    119: 'Injector Needle Lift Sensor #2',
    120: 'Coolant System Thermostat',
    121: 'Engine Automatic Start Alarm',
    122: 'Engine Automatic Start Lamp',
    123: 'Engine Automatic Start Safety Interlock Circuit',
    124: 'Engine Automatic Start Failed (Engine)',
    125: 'Fuel Heater Driver Signal',
    126: 'Fuel Pump Pressurizing Assembly #1',
    127: 'Fuel Pump Pressurizing Assembly #2',
    128: 'Starter Solenoid Lockout Relay Driver Circuit',
    129: 'Cylinder #1 Exhaust Gas Port Temperature',
    130: 'Cylinder #2 Exhaust Gas Port Temperature',
    131: 'Cylinder #3 Exhaust Gas Port Temperature',
    132: 'Cylinder #4 Exhaust Gas Port Temperature',
    133: 'Cylinder #5 Exhaust Gas Port Temperature',
    134: 'Cylinder #6 Exhaust Gas Port Temperature',
    135: 'Cylinder #7 Exhaust Gas Port Temperature',
    136: 'Cylinder #8 Exhaust Gas Port Temperature',
    137: 'Cylinder #9 Exhaust Gas Port Temperature',
    138: 'Cylinder #10 Exhaust Gas Port Temperature',
    139: 'Cylinder #11 Exhaust Gas Port Temperature',
    140: 'Cylinder #12 Exhaust Gas Port Temperature',
    141: 'Cylinder #13 Exhaust Gas Port Temperature',
    142: 'Cylinder #14 Exhaust Gas Port Temperature',
    143: 'Cylinder #15 Exhaust Gas Port Temperature',
    144: 'Cylinder #16 Exhaust Gas Port Temperature',
    145: 'Adaptive Cruise Control Mode',
    146: 'Exhaust Gas Recirculation (EGR) Valve #1 Mechanism',
    147: 'Variable Nozzle Turbocharger (VNT) Mechanism',
    148: 'Engine (Compression) Brake Output #4',
    149: 'Engine (Compression) Brake Output #5',
    255: 'Engine (Compression) Brake Output #6',
    256: 'Reserved',
    257: 'Auxiliary output device driver # 9',
    258: 'Auxiliary output device driver # 10',
    259: 'Auxiliary output device driver # 11',
    260: 'Auxiliary output device driver # 12',
    261: 'Auxiliary output device driver # 13',
    262: 'Auxiliary output device driver # 14',
    263: 'Auxiliary output device driver # 15',
    264: 'Auxiliary output device driver # 16',
    265: 'Auxiliary output device driver # 17',
    266: 'Exhaust Gas Recirculation (EGR) Valve #2 Mechanism',
    267: 'Auxiliary PWM Driver #5',
    268: 'Auxiliary PWM Driver #6',
    269: 'Turbocharger Nozzle Position Sensor',
    270: 'Turbocharger Compressor Discharge Temperature Sensor',
    271: 'Charge Air Cooler Bypass Control',
    272: 'Charge Air Cooler Air Outlet Temperature Sensor',
    273: 'Charge Air Cooler Air Outlet Pressure Sensor',
    274: 'Combustion Air Humidity Sensor',
    275: 'Auxiliary Engine Cooling System Control Output',
    276: 'Inlet Air Pre-Cleaner Control Output',
    277: 'Exhaust Gas Recirculation (EGR) Mass Flow Sensor',
    278: 'Fuel Shutoff Valve #2',
    279: 'Fuel Leakage Sensor #1',
    280: 'Fuel Leakage Sensor #2',
    281: 'Exhaust Gas Recirculation (EGR) Check Valve(s)',
    282: 'Exhaust Gas Recirculation (EGR) Cooler',
    283: 'Intake Valve Actuation System Oil Pressure Control Valve',
    284: 'Engine Coolant Diverter Valve',
    285: 'Intake Valve Actuator #1',
    286: 'Intake Valve Actuator #2',
    287: 'Intake Valve Actuator #3',
    288: 'Intake Valve Actuator #4',
    289: 'Intake Valve Actuator #5',
    290: 'Intake Valve Actuator #6',
    291: 'Intake Valve Actuator #7',
    292: 'Intake Valve Actuator #8',
    293: 'Intake Valve Actuator #9',
    294: 'Intake Valve Actuator #10',
    295: 'Intake Valve Actuator #11',
    296: 'Intake Valve Actuator #12',
    297: 'Intake Valve Actuator #13',
    298: 'Intake Valve Actuator #14',
    299: 'Intake Valve Actuator #15',
    300: 'Intake Valve Actuator #16',
    301: 'Intake Valve Actuator #17',
    302: 'Intake Valve Actuator #18',
    303: 'Intake Valve Actuator #19',
    304: 'Intake Valve Actuator #20',
    305: 'Gas Control Valve # 1 Outlet Pressure (Natural Gas)',
    306: 'Engine Coolant # 2 Pressure #1',
    307: 'Mixer Inlet Relative Humidity',
    308: 'Fuel Rack Position # 2',
    309: 'Turbocharger Compressor Outlet # 1 Pressure',
    310: 'Waste Engine Oil Reservoir Level',
    311: 'Engine Oil Level # 2 Remote Reservoir',
    312: 'Coolant Level # 2',
    313: 'Injector Cylinder, Multiple',
    314: 'Turbocharger #1 Compressor Inlet Pressure (absolute)',
    315: 'External Engine Protection Input #2',
    316: 'Service Indication Lamp',
    317: 'Injector Supply Voltage',
    318: 'Particulate Trap Intake Gas Temperature Bank 1',
    319: 'Particulate Trap Intake Gas Temperature Bank 2',
    320: 'Particulate Trap Outlet Gas Temperature Bank 1',
    321: 'Particulate Trap Outlet Gas Temperature Bank 2',
    322: 'Particulate Trap Intermediate Gas Temperature Bank 1',
    323: 'Particulate Trap Intermediate Gas Temperature Bank 2',
    324: 'Particulate Trap Differential Pressure Bank 1',
    325: 'Particulate Trap Differential Pressure Bank 2',
    326: 'Exhaust Gas Temperature 1',
    327: 'Exhaust Gas Temperature 2',
    328: 'Exhaust Gas Temperature 3',
    329: 'Exhaust Gas Temperature 1 Bank 2',
    330: 'Exhaust Gas Temperature 2 Bank 2',
    331: 'Exhaust Gas Temperature 3 Bank 2',
    332: 'Aftertreatment #1 Fuel Pressure',
    333: 'Aftertreatment #1 Fuel Pressure Control Actuator',
    334: 'Aftertreatment #1 Fuel Enable Actuator',
    335: 'Aftertreatment #1 Ignition',
    336: 'Aftertreatment #2 Fuel Pressure',
    337: 'Aftertreatment #2 Fuel Pressure Control Actuator',
    338: 'Aftertreatment #2 Fuel Enable Actuator',
    339: 'Aftertreatment #2 Ignition',
    340: 'Aftertreatment #1 Air Enable Actuator',
    341: 'Aftertreatment #1 Purge Air Actuator',
    342: 'Aftertreatment #1 Atomization Air Actuator',
    343: 'Aftertreatment #1 Air System Relay',
    344: 'Aftertreatment #2 Air Enable Actuator',
    345: 'Aftertreatment #2 Purge Air Actuator',
    346: 'Aftertreatment #2 Atomization Air Actuator',
    347: 'Aftertreatment #2 Air System Relay',
    348: 'Aftertreatment #1 Supply Air Pressure',
    349: 'Aftertreatment #1 Purge Air Pressure',
    350: 'Aftertreatment #1 Air Pressure Control Actuator',
    351: 'Aftertreatment #1 Air Pressure Actuator Position',
    352: 'Aftertreatment #2 Supply Air Pressure',
    353: 'Aftertreatment #2 Purge Air Pressure',
    354: 'Aftertreatment #2 Air Pressure Control Actuator',
    355: 'Aftertreatment #2 Air Pressure Actuator Position',
    356: 'Aftertreatment #1 Failed to Ignite',
    357: 'Aftertreatment #1 Loss of Ignition',
    358: 'Aftertreatment #2 Failed to Ignite',
    359: 'Aftertreatment #2 Loss of Ignition',
    360: 'Aftertreatment #1 Regeneration Manually Disabled',
    361: 'Aftertreatment #2 Regeneration Manually Disabled',
    362: 'Injector Cylinder #1, Actuator #2',
    363: 'Injector Cylinder #2, Actuator #2',
    364: 'Injector Cylinder #3, Actuator #2',
    365: 'Injector Cylinder #4, Actuator #2',
    366: 'Injector Cylinder #5, Actuator #2',
    367: 'Injector Cylinder #6, Actuator #2',
    368: 'Injector Cylinder #7, Actuator #2',
    369: 'Injector Cylinder #8, Actuator #2',
    370: 'Aftertreatment #1 Particulate Trap Intake Pressure',
    371: 'Aftertreatment #1 Particulate Trap Outlet Pressure',
    372: 'Ambient Air Density',
    373: 'Aftertreatment #1 Secondary Air Differential Pressure',
    374: 'Aftertreatment #2 Secondary Air Differential Pressure',
    375: 'Aftertreatment #1 Secondary Air Temperature',
    376: 'Aftertreatment #2 Secondary Air Temperature',
    377: 'Aftertreatment #1 Secondary Air Pressure',
    378: 'Aftertreatment #2 Secondary Air Pressure',
    379: 'Oil Scavenge Pump',
    380: 'Catalyst 1 System Monitor',
    381: 'Aftertreatment 1 Fuel Drain Actuator',
    382: 'Aftertreatment 1 Fuel Injector 1',
    383: 'Particulate Matter Trap Monitor',
    384: 'Engine Turbocharger 1 Turbine Inlet Temperature',
    385: 'Accelerator Pedal #1 Channel 2',
    386: 'Aftertreatment #1 Purge Air Pressure',
    387: 'Aftertreatment #1 Secondary Air Mass Flow',
    388: 'Particulate Trap Active Regeneration Inhibited Due to Permanent System Lockout',
    389: 'Aftertreatment 1 Fuel Rate',
    390: 'Particulate Trap Active Regeneration Inhibited Status',
    391: 'Engine Exhaust Gas Recirculation (EGR) System Monitor',
    392: 'Engine Injector Bank 1',
    393: 'Particulate Trap Active Regeneration Inhibited Due to Inhibit Switch',
    394: 'Particulate Trap Active Regeneration Inhibited Due to Temporary System Lockout',
    395: 'Engine Air Shutoff Command Status',
    396: 'Aftertreatment 1 Ignition Transformer Secondary Output',
    range(397, 511): 'Reserved',
})


# Transmission SIDs(MID = 130, 176, 223)
transmission_sids = RangeDict({
    0: 'Reserved',
    1: 'C1 Solenoid Valve',
    2: 'C2 Solenoid Valve',
    3: 'C3 Solenoid Valve',
    4: 'C4 Solenoid Valve',
    5: 'C5 Solenoid Valve',
    6: 'C6 Solenoid Valve',
    7: 'Lockup Solenoid Valve',
    8: 'Forward Solenoid Valve',
    9: 'Low Signal Solenoid Valve',
    10: 'Retarder Enable Solenoid Valve',
    11: 'Retarder Modulation Solenoid Valve',
    12: 'Retarder Response Solenoid Valve',
    13: 'Differential Lock Solenoid Valve',
    14: 'Engine/Transmission Match',
    15: 'Retarder Modulation Request Sensor',
    16: 'Neutral Start Output',
    17: 'Turbine Speed Sensor',
    18: 'Primary Shift Selector',
    19: 'Secondary Shift Selector',
    20: 'Special Function Inputs',
    21: 'C1 Clutch Pressure Indicator',
    22: 'C2 Clutch Pressure Indicator',
    23: 'C3 Clutch Pressure Indicator',
    24: 'C4 Clutch Pressure Indicator',
    25: 'C5 Clutch Pressure Indicator',
    26: 'C6 Clutch Pressure Indicator',
    27: 'Lockup Clutch Pressure Indicator',
    28: 'Forward Range Pressure Indicator',
    29: 'Neutral Range Pressure Indicator',
    30: 'Reverse Range Pressure Indicator',
    31: 'Retarder Response System Pressure Indicator',
    32: 'Differential Lock Clutch Pressure Indicator',
    33: 'Multiple Pressure Indicators',
    34: 'Reverse Switch',
    35: 'Range High Actuator',
    36: 'Range Low Actuator',
    37: 'Splitter Direct Actuator',
    38: 'Splitter Indirect Actuator',
    39: 'Shift Finger Rail Actuator 1',
    40: 'Shift Finger Gear Actuator 1',
    41: 'Upshift Request Switch',
    42: 'Downshift Request Switch',
    43: 'Torque Converter Interrupt Actuator',
    44: 'Torque Converter Lockup Actuator',
    45: 'Range High Indicator',
    46: 'Range Low Indicator',
    47: 'Shift Finger Neutral Indicator',
    48: 'Shift Finger Engagement Indicator',
    49: 'Shift Finger Center Rail Indicator',
    50: 'Shift Finger Rail Actuator 2',
    51: 'Shift Finger Gear Actuator 2',
    52: 'Hydraulic System',
    53: 'Defuel Actuator',
    54: 'Inertia Brake Actuator',
    55: 'Clutch Actuator',
    56: 'Auxiliary Range Mechanical System',
    57: 'Shift Console Data Link',
    58: 'Main Box Shift Engagement System',
    59: 'Main Box Rail Selection System',
    60: 'Main Box Shift Neutralization System',
    61: 'Auxiliary Splitter Mechanical System',
    62: 'Transmission Controller Power Relay',
    63: 'Output Shaft Speed Sensor',
    64: 'Throttle Position Device',
    range(65, 150): 'Reserved',
})


# Brake SIDs (MIDs = 136, 137, 138, 139, 246, 247)
brake_sids = RangeDict({
    0: 'Reserved',
    1: 'Wheel Sensor ABS Axle 1 Left',
    2: 'Wheel Sensor ABS Axle 1 Right',
    3: 'Wheel Sensor ABS Axle 2 Left',
    4: 'Wheel Sensor ABS Axle 2 Right',
    5: 'Wheel Sensor ABS Axle 3 Left',
    6: 'Wheel Sensor ABS Axle 3 Right',
    7: 'Pressure Modulation Valve ABS Axle 1 Left',
    8: 'Pressure Modulation Valve ABS Axle 1 Right',
    9: 'Pressure Modulation Valve ABS Axle 2 Left',
    10: 'Pressure Modulation Valve ABS Axle 2 Right',
    11: 'Pressure Modulation Valve ABS Axle 3 Left',
    12: 'Pressure Modulation Valve ABS Axle 3 Right',
    13: 'Retarder Control Relay',
    14: 'Relay Diagonal 1',
    15: 'Relay Diagonal 2',
    16: 'Mode Switch ABS',
    17: 'Mode Switch ASR',
    18: 'DIF 1—ASR Valve',
    19: 'DIF 2—ASR Valve',
    20: 'Pneumatic Engine Control',
    21: 'Electronic Engine Control (Servomotor)',
    22: 'Speed Signal Input',
    23: 'Tractor ABS Warning Light Bulb',
    24: 'ASR Light Bulb',
    25: 'Wheel Sensor, ABS Axle 1 Average',
    26: 'Wheel Sensor, ABS Axle 2 Average',
    27: 'Wheel Sensor, ABS Axle 3 Average',
    28: 'Pressure Modulator, Drive Axle Relay Valve',
    29: 'Pressure Transducer, Drive Axle Relay Valve',
    30: 'Master Control Relay',
    31: 'Trailer Brake Slack Out of Adjustment Forward Axle Left',
    32: 'Trailer Brake Slack Out of Adjustment Forward axle Right',
    33: 'Trailer Brake Slack Out of Adjustment Rear Axle Left',
    34: 'Trailer Brake Slack Out of Adjustment Rear Axle Right',
    35: 'Tractor Brake Slack Out of Adjustment Axle 1 Left',
    36: 'Tractor Brake Slack Out of Adjustment Axle 1 Right',
    37: 'Tractor Brake Slack Out of Adjustment Axle 2 Left',
    38: 'Tractor Brake Slack Out of Adjustment Axle 2 Right',
    39: 'Tractor Brake Slack Out of Adjustment Axle 3 Left',
    40: 'Tractor Brake Slack Out of Adjustment Axle 3 Right',
    41: 'Ride Height Relay',
    42: 'Hold Modulator Valve Solenoid Axle 1 Left',
    43: 'Hold Modulator Valve Solenoid Axle 1 Right',
    44: 'Hold Modulator Valve Solenoid Axle 2 Left',
    45: 'Hold Modulator Valve Solenoid Axle 2 Right',
    46: 'Hold Modulator Valve Solenoid Axle 3 Left',
    47: 'Hold Modulator Valve Solenoid Axle 3 Right',
    48: 'Dump Modulator Valve Solenoid Axle 1 Left',
    49: 'Dump Modulator Valve Solenoid Axle 1 Right',
    50: 'Dump Modulator Valve Solenoid Axle 2 Left',
    51: 'Dump Modulator Valve Solenoid Axle 2 Right',
    52: 'Dump Modulator Valve Solenoid Axle 3 Left',
    53: 'Dump Modulator Valve Solenoid Axle 3 Right',
    54: 'Hydraulic Pump Motor',
    55: 'Brake Light Switch 1',
    56: 'Brake Light Switch 2',
    57: 'Electronic Pressure Control, Axle 1',
    58: 'Pneumatic Back-up Pressure Control, Axle 1',
    59: 'Brake Pressure Sensing, Axle 1',
    60: 'Electronic Pressure Control, Axle 2',
    61: 'Pneumatic Back-up Pressure Control, Axle 2',
    62: 'Brake Pressure Sensing, Axle 2',
    63: 'Electronic Pressure Control, Axle 3',
    64: 'Pneumatic Back-up Pressure Control, Axle 3',
    65: 'Brake Pressure Sensing, Axle 3',
    66: 'Electronic Pressure Control, Trailer Control',
    67: 'Pneumatic Back-up Pressure Control, Trailer Control',
    68: 'Brake Pressure Sensing, Trailer Control',
    69: 'Axle Load Sensor',
    70: 'Lining Wear Sensor, Axle 1 Left',
    71: 'Lining Wear Sensor, Axle 1 Right',
    72: 'Lining Wear Sensor, Axle 2 Left',
    73: 'Lining Wear Sensor, Axle 2 Right',
    74: 'Lining Wear Sensor, Axle 3 Left',
    75: 'Lining Wear Sensor, Axle 3 Right',
    76: 'Brake Signal Transmitter',
    77: 'Brake Signal Sensor 1',
    78: 'Brake Signal Sensor 2',
    79: 'Tire Dimension Supervision',
    80: 'Vehicle Deceleration Control',
    81: 'Trailer ABS Warning Light Bulb',
    82: 'Brake Torque Output Axle 1 Left',
    83: 'Brake Torque Output Axle 1 Right',
    84: 'Brake Torque Output Axle 2 Left',
    85: 'Brake Torque Output Axle 2 Right',
    86: 'Brake Torque Output Axle 3 Left',
    87: 'Brake Torque Output Axle 3 Right',
    88: 'Vehicle Dynamic Stability Control System (VDC)',
    89: 'Steering Angle Sensor',
    90: 'Voltage Supply for Stability Control System',
    91: 'Brake Lining Display',
    92: 'Pressure Limitation Valve',
    93: 'Auxiliary Valve',
    94: 'Hill holder System',
    95: 'Voltage Supply, Lining Wear Sensors, Axle 1',
    96: 'Voltage Supply, Lining Wear Sensors, Axle 2',
    97: 'Voltage Supply, Lining Wear Sensors, Axle 3',
    98: 'Reference Ground Connection',
    99: 'Lateral Accelerometer',
    100: 'Brake Light Relay',
    101: 'Brake Warning Light Bulb',
    102: 'Differential Lock control output (transfer case)',
    103: 'Yaw Rate Sensor',
    104: 'Service Odometer',
    range(105, 150): 'Reserved',
})


# Instrument Panel SIDs (MID = 140, 234)
instrument_panel_sids = RangeDict({
    0: 'Reserved',
    1: 'Left Fuel Level Sensor',
    2: 'Right Fuel Level Sensor',
    3: 'Fuel Feed Rate Sensor',
    4: 'Fuel Return Rate Sensor',
    5: 'Tachometer Gauge Coil',
    6: 'Speedometer Gauge Coil',
    7: 'Turbocharger Air Pressure Gauge Coil',
    8: 'Fuel Pressure Gauge Coil',
    9: 'Fuel Level Gauge Coil',
    10: 'Second Fuel Level Gauge Coil',
    11: 'Engine Oil Pressure Gauge Coil',
    12: 'Engine Oil Temperature Gauge Coil',
    13: 'Engine Coolant Temperature Gauge Coil',
    14: 'Pyrometer Gauge Coil',
    16: 'Transmission Oil Pressure Gauge Coil',
    15: 'Transmission Oil Temperature Gauge Coil',
    17: 'Forward Rear Axle Temperature Gauge Coil',
    18: 'Rear Rear Axle Temperature Gauge Coil',
    19: 'Voltmeter Gauge Coil',
    20: 'Primary Air Pressure Gauge Coil',
    21: 'Secondary Air Pressure Gauge Coil',
    22: 'Ammeter Gauge Coil',
    23: 'Air Application Gauge Coil',
    24: 'Air Restriction Gauge Coil',
    range(25, 150): 'Reserved',
})


# Vehicle Management SIDs (MID = 142, 187, 188)
vehicle_management_sids = RangeDict({
    0: 'Reserved',
    1: 'Timing Sensor',
    2: 'Timing Actuator',
    3: 'Fuel Rack Position Sensor',
    4: 'Fuel Rack Actuator',
    5: 'Oil Level Indicator Output',
    6: 'Tachometer Drive Output',
    7: 'Speedometer Drive Output',
    8: 'PWM Input (ABS/ASR)',
    9: 'PWM Output',
    10: 'Auxiliary Output #1',
    11: 'Auxiliary Output #2',
    12: 'Auxiliary Output #3',
    13: 'Auxiliary Output #4',
    14: 'Auxiliary Output #5',
    15: 'Power Relay Control Output',
    16: '“Neutral” Power Relay Control Output',
    17: 'Starter Relay Control Output',
    18: 'Transmission Shift Control Valve #1 Output',
    19: 'Transmission Shift Control Valve #2 Output',
    20: 'Differential Lock Control Valve #1 Output',
    21: 'Differential Lock Control Valve #2 Output',
    22: 'Windshield Wiper ON Relay Control Output',
    23: 'Windshield Wiper Speed Select Output',
    24: 'Mirror Heat Control Output',
    25: 'Driver Door “Lock” Output',
    26: 'Driver Door “Unlock” Output',
    27: 'Switch Diagnostic Output',
    28: 'Horn Control Output',
    29: '“Wake Up” Output',
    30: 'Interior Lamps Output',
    31: 'Fan Override Indicator Lamp Output',
    32: 'Low Air Pressure Indicator Relay Output',
    33: 'Maintenance Lamp Output',
    34: 'Battery Monitor Load #1 Control Output',
    35: 'Battery Monitor Load #2 Control Output',
    36: 'Headlamp Low Beam Left #1 Output',
    37: 'Headlamp Low Beam Left #2 Output',
    38: 'Headlamp Low Beam Right #1 Output',
    39: 'Headlamp Low Beam Right #2 Output',
    range(40, 150): 'Reserved',
})


# Fuel System SIDs (MID = 143)
fuel_system_sids = RangeDict({
    0: 'Reserved',
    1: 'Injector Cylinder #1',
    2: 'Injector Cylinder #2',
    3: 'Injector Cylinder #3',
    4: 'Injector Cylinder #4',
    5: 'Injector Cylinder #5',
    6: 'Injector Cylinder #6',
    7: 'Injector Cylinder #7',
    8: 'Injector Cylinder #8',
    9: 'Injector Cylinder #9',
    10: 'Injector Cylinder #10',
    11: 'Injector Cylinder #11',
    12: 'Injector Cylinder #12',
    13: 'Injector Cylinder #13',
    14: 'Injector Cylinder #14',
    15: 'Injector Cylinder #15',
    16: 'Injector Cylinder #16',
    17: 'Fuel Shutoff Valve',
    18: 'Fuel Control Valve',
    19: 'Throttle Bypass Valve',
    20: 'Timing Actuator',
    21: 'Engine Position Sensor',
    22: 'Timing Sensor',
    23: 'Rack Actuator',
    24: 'Rack Position Sensor',
    25: 'External Engine Protection Input',
    26: 'Auxiliary Output Device Driver',
    27: 'Cooling Fan Drive Output',
    28: 'Engine (Compression) Brake Output #1',
    29: 'Engine (Compression) Brake Output #2',
    30: 'Engine (Exhaust) Brake Output',
    31: 'Pressure Control Valve #1',
    32: 'Pressure Control Valve #2',
    range(33, 150): 'Reserved',
})


# Cab Climate Control SIDs (MID = 146, 200)
cab_climate_control_sids = RangeDict({
    0: 'Reserved',
    1: 'HVAC Unit Discharge Temperature Sensor',
    2: 'Evaporator Temperature Sensor',
    3: 'Solar Load Sensor #1',
    4: 'Solar Load Sensor #2',
    5: 'Fresh/Recirculation Air Intake Door Actuator',
    6: 'Mode Door #1 Actuator',
    7: 'Mode Door #2 Actuator',
    8: 'Mode Door #3 Actuator',
    9: 'Blend Door Actuator',
    10: 'Blower Motor',
    11: 'A/C Clutch Relay',
    12: 'Water Valve',
    13: 'Heater Exchanger Temperature Sensor',
    14: 'In Cabin Temperature Sensor Blower',
    15: 'Blower Clutch',
    16: 'Stepper Motor Phase 1',
    17: 'Stepper Motor Phase 2',
    18: 'Stepper Motor Phase 3',
    19: 'Stepper Motor Phase 4',
    20: 'Refrigerant Evaporator Inlet Temperature Sensor',
    21: 'Refrigerant Evaporator Outlet Temperature Sensor',
    22: 'Refrigerant Evaporator Inlet Pressure Sensor',
    23: 'Refrigerant Evaporator Outlet Pressure Sensor',
    24: 'Refrigerant Compressor Inlet Temperature Sensor',
    25: 'Refrigerant Compressor Outlet Temperature Sensor',
    26: 'Refrigerant Compressor Inlet Pressure Sensor',
    27: 'Refrigerant Compressor Outlet Pressure Sensor',
    28: 'Refrigerant Condenser Outlet Temperature Sensor',
    29: 'Refrigerant Condenser Outlet Pressure Sensor',
    30: 'Climate Control Air Filter Differential Pressure Sensor',
    range(31, 150): 'Reserved',
})


# Suspension SIDs (MID = 150, 151)
suspension_sids = RangeDict({
    0: 'Reserved',
    1: 'Solenoid Valve Axle 1 Right',
    2: 'Solenoid Valve Axle 1 Left',
    3: 'Solenoid Valve Axle 2 Right',
    4: 'Solenoid Valve Axle 2 Left',
    5: 'Solenoid Valve Axle 3 Right',
    6: 'Solenoid Valve Axle 3 Left',
    7: 'Solenoid Valve Central (Lowering/Lifting Control)',
    8: 'Solenoid Valve for Lifting the Lifting/Trailing Axle',
    9: 'Solenoid Valve for Lowering the Lifting/Trailing Axle',
    10: 'Solenoid Valve for Control of the Lift Bellow',
    11: 'Solenoid Valve for Starting Lock',
    12: 'Solenoid Valve for Door Release',
    13: 'Solenoid Valve for Mainflow Throttle',
    14: 'Solenoid Valve for Transverse Lock/Throttle',
    15: 'Solenoid Valve for Automatic Load-Dependent Brake-Power Balance',
    16: 'Height Sensor Axle 1 Right',
    17: 'Height Sensor Axle 1 Left',
    18: 'Height Sensor Axle 2 Right',
    19: 'Height Sensor Axle 2 Left',
    20: 'Height Sensor Axle 3 Right',
    21: 'Height Sensor Axle 3 Left',
    22: 'Pressure Sensor Axle 1 Right',
    23: 'Pressure Sensor Axle 1 Left',
    24: 'Pressure Sensor Axle 2 Right',
    25: 'Pressure Sensor Axle 2 Left',
    26: 'Pressure Sensor Axle 3 Right',
    27: 'Pressure Sensor Axle 3 Left',
    28: 'Pressure Sensor Lift Bellow',
    29: 'Sidewalk Detector Sensor',
    30: 'Switch for Maximum Permanent Permissible Pressure',
    31: 'Switch for Maximum Temporary Permissible Pressure',
    32: 'Speed Signal Input',
    33: 'Remote Control Unit #1',
    34: 'Central Valve Relay',
    35: 'Auxiliary Tank Control',
    36: 'Exterior Kneel (warning lamp and audible alarm)',
    37: 'Wheel Chair Lift Inhibit',
    38: 'Checksum ECU Specific Data',
    39: 'Checksum Parameter Data',
    40: 'Checksum Calibration Data Level Sensors',
    41: 'Checksum Calibration Data Pressure Sensors',
    42: 'Checksum Maximum Axle Load Data',
    43: 'Central 3/2 Solenoid Valve Axle 3',
    44: 'Central 3/2 Solenoid Valve Front Axle',
    45: 'Pressure Sensor Brake Pressure',
    46: 'Power Supply for Pressure Sensors',
    47: 'Power Supply for Remote Controls',
    48: 'Remote Control #1 Data Line',
    49: 'Remote Control #1 Clock Line',
    50: 'Remote Control #2 Data Line',
    51: 'Remote Control #2 Clock Line',
    52: 'Remote Control Unit #2',
    53: 'Power Supply for Solenoid Valves',
    54: 'Proportional Valve Front Axle Left',
    55: 'Proportional Valve Front Axle Right',
    56: 'Proportional Valve Drive Axle Left',
    57: 'Proportional Valve Drive Axle Right',
    58: 'Proportional Valve Axle 3 Left',
    59: 'Proportional Valve Axle 3 Right',
    range(60, 150): 'Reserved',
})


# Park Brake Controller SIDs (MID = 157)
park_brake_controller_sids = RangeDict({
    0: 'Reserved',
    1: 'Pressure Sender #1',
    2: 'Pressure Sender #2',
    3: 'Solenoid Control #1',
    4: 'Solenoid Control #2',
    5: 'Solenoid Control #3',
    6: 'Solenoid Control #4',
    7: 'Operator Control Switch #1 (input)',
    8: 'Operator Control Switch #2 (input)',
    9: 'Operator Station',
    10: 'Passenger Station',
    11: 'Interior Station',
    12: 'Exterior Station',
    13: 'Light Sequence Control',
    14: 'Warning light #1',
    15: 'Warning light #2',
    16: 'Speed Sense Comparator',
    17: 'Series Latch Monitor',
    18: 'Expansion ECU Station',
    19: 'Aux Switch Input #1',
    20: 'Aux Switch Input #2',
    21: 'Diagnostic Input',
    22: 'Aux Data Link (I2C)',
    23: 'Solenoid Supply #1',
    24: 'Solenoid Supply #2',
    25: 'Solenoid Supply #3',
    26: 'Solenoid Supply #4',
    27: 'Operator Control Switch #1 (output)',
    28: 'Operator Control Switch #2 (output)',
    29: 'Operator Control Switch Aux',
    30: 'Aux Output #1',
    31: 'Aux Output # 2',
    32: 'Aux Output # 3',
    33: 'Aux Output # 4',
    34: 'Aux Output # 5',
    35: 'Aux Output # 6',
    36: 'Aux Output # 7',
    37: 'Diagnostic Output',
    38: 'Pressure Control Modulator',
    39: 'Series Latch Control',
    40: 'Brownout Voltage Sequence Control',
    range(41, 150): 'Reserved',
})


# Vehicle Navigation SIDs (MID = 162, 191)
vehicle_navigation_sids = RangeDict({
    0: 'Reserved',
    1: 'Dead Reckoning Unit',
    2: 'Loran Receiver',
    3: 'Global Positioning System (GPS)',
    4: 'Integrated Navigation Unit',
    range(5, 150): 'Reserved',
})


# Vehicle Security SIDs (MID = 163)
vehicle_security_sids = RangeDict({
    0: 'Reserved',
    1: 'Transceiver Antenna',
    2: 'Security Transponder',
    range(3, 150): 'Reserved',
})


# Tire SIDs (MID = 166, 168, 169, 186)
tire_sids = RangeDict({
    0: 'Reserved',
    1: 'Operator Control Panel (OCP)',
    2: 'Pneumatic Control Unit (PCU)',
    3: 'PCU Steer Solenoid',
    4: 'PCU Drive Solenoid',
    5: 'PCU Solenoid Trailer #1, Tag #1, or Push #1',
    6: 'PCU Supply Solenoid',
    7: 'PCU Control Solenoid',
    8: 'PCU Deflate Solenoid',
    9: 'Pneumatic—Steer Channel',
    10: 'Pneumatic—Drive Channel',
    11: 'Pneumatic—Trailer #1, Tag #1, or Push #1 Channel',
    12: 'Drive Axle Manifold Deflation Solenoid',
    13: 'Steer Axle Manifold Deflation Solenoid',
    14: 'PCU Solenoid Trailer #2, Tag #2, or Push #2',
    15: 'Brake Priority Pressure Switch',
    16: 'Pneumatic-Trailer #2, Tag #2, or Push #2 Channel',
    17: 'Wiring Harness',
    18: 'Tire Pressure Sensor - # 1',
    19: 'Tire Pressure Sensor - # 2',
    20: 'Tire Pressure Sensor - # 3',
    21: 'Tire Pressure Sensor - # 4',
    22: 'Tire Pressure Sensor - # 5',
    23: 'Tire Pressure Sensor - # 6',
    24: 'Tire Pressure Sensor - # 7',
    25: 'Tire Pressure Sensor - # 8',
    26: 'Tire Pressure Sensor - # 9',
    27: 'Tire Pressure Sensor - # 10',
    28: 'Tire Pressure Sensor - # 11',
    29: 'Tire Pressure Sensor - # 12',
    30: 'Tire Pressure Sensor - # 13',
    31: 'Tire Pressure Sensor - # 14',
    32: 'Tire Pressure Sensor - # 15',
    33: 'Tire Pressure Sensor - # 16',
    34: 'Tire Temperature Sensor - # 1',
    35: 'Tire Temperature Sensor - # 2',
    36: 'Tire Temperature Sensor - # 3',
    37: 'Tire Temperature Sensor - # 4',
    38: 'Tire Temperature Sensor - # 5',
    39: 'Tire Temperature Sensor - # 6',
    40: 'Tire Temperature Sensor - # 7',
    41: 'Tire Temperature Sensor - # 8',
    42: 'Tire Temperature Sensor - # 9',
    43: 'Tire Temperature Sensor - # 10',
    44: 'Tire Temperature Sensor - # 11',
    45: 'Tire Temperature Sensor - # 12',
    46: 'Tire Temperature Sensor - # 13',
    47: 'Tire Temperature Sensor - # 14',
    48: 'Tire Temperature Sensor - # 15',
    49: 'Tire Temperature Sensor - # 16',
    50: 'Tire Sensor Voltage - # 1',
    51: 'Tire Sensor Voltage - # 2',
    52: 'Tire Sensor Voltage - # 3',
    53: 'Tire Sensor Voltage - # 4',
    54: 'Tire Sensor Voltage - # 5',
    55: 'Tire Sensor Voltage - # 6',
    56: 'Tire Sensor Voltage - # 7',
    57: 'Tire Sensor Voltage - # 8',
    58: 'Tire Sensor Voltage - # 9',
    59: 'Tire Sensor Voltage - # 10',
    60: 'Tire Sensor Voltage - # 11',
    61: 'Tire Sensor Voltage - # 12',
    62: 'Tire Sensor Voltage - # 13',
    63: 'Tire Sensor Voltage - # 14',
    64: 'Tire Sensor Voltage - # 15',
    65: 'Tire Sensor Voltage - # 16',
    range(66, 150): 'Reserved',
})


# Particulate Trap SIDs (MID = 177)
particulate_trap_sids = RangeDict({
    0: 'Reserved',
    1: 'Particulate Trap Intake Gas Temperature Bank 1',
    2: 'Particulate Trap Intake Gas Temperature Bank 2',
    3: 'Particulate Trap Outlet Gas Temperature Bank 1',
    4: 'Particulate Trap Outlet Gas Temperature Bank 2',
    5: 'Particulate Trap Intermediate Gas Temperature Bank 1',
    6: 'Particulate Trap Intermediate Gas Temperature Bank 2',
    7: 'Particulate Trap Differential Pressure Bank 1',
    8: 'Particulate Trap Differential Pressure Bank 2',
    9: 'Exhaust Gas Temperature 1',
    10: 'Exhaust Gas Temperature 2',
    11: 'Exhaust Gas Temperature 3',
    12: 'Exhaust Gas Temperature 1 Bank 2',
    13: 'Exhaust Gas Temperature 2 Bank 2',
    14: 'Exhaust Gas Temperature 3 Bank 2',
    15: 'Aftertreatment #1 Fuel Pressure',
    16: 'Aftertreatment #1 Fuel Pressure Control Actuator',
    17: 'Aftertreatment #1 Fuel Enable Actuator',
    18: 'Aftertreatment #1 Ignition',
    19: 'Aftertreatment #2 Fuel Pressure',
    20: 'Aftertreatment #2 Fuel Pressure Control Actuator',
    21: 'Aftertreatment #2 Fuel Enable Actuator',
    22: 'Aftertreatment #2 Ignition',
    23: 'Aftertreatment #1 Air Enable Actuator',
    24: 'Aftertreatment #1 Purge Air Actuator',
    25: 'Aftertreatment #1 Atomization Air Actuator',
    26: 'Aftertreatment #1 Air System Relay',
    27: 'Aftertreatment #2 Air Enable Actuator',
    28: 'Aftertreatment #2 Purge Air Actuator',
    29: 'Aftertreatment #2 Atomization Air Actuator',
    30: 'Aftertreatment #2 Air System Relay',
    31: 'Aftertreatment #1 Supply Air Pressure',
    32: 'Aftertreatment #1 Purge Air Pressure',
    33: 'Aftertreatment #1 Air Pressure Control Actuator',
    34: 'Aftertreatment #1 Air Pressure Actuator Position',
    35: 'Aftertreatment #2 Supply Air Pressure',
    36: 'Aftertreatment #2 Purge Air Pressure',
    37: 'Aftertreatment #2 Air Pressure Control Actuator',
    38: 'Aftertreatment #2 Air Pressure Actuator Position',
    39: 'Aftertreatment #1 Failed to Ignite',
    40: 'Aftertreatment #1 Loss of Ignition',
    41: 'Aftertreatment #2 Failed to Ignite',
    42: 'Aftertreatment #2 Loss of Ignition',
    43: 'Aftertreatment #1 Regeneration Manually Disabled',
    44: 'Aftertreatment #2 Regeneration Manually Disabled',
    45: 'Aftertreatment #1 Particulate Trap Intake Pressure',
    46: 'Aftertreatment #1 Particulate Trap Outlet Pressure',
    47: 'Oil Scavenge Pump',
    48: 'Catalyst 1 System Monitor',
    49: 'Aftertreatment 1 Fuel Drain Actuator',
    50: 'Aftertreatment 1 Fuel Injector 1',
    51: 'Particulate Matter Trap Monitor',
    52: 'Aftertreatment #1 Purge Air Pressure',
    53: 'Aftertreatment #1 Secondary Air Mass Flow',
    54: 'Particulate Trap Active Regeneration Inhibited Due to Permanent System Lockout',
    55: 'Aftertreatment 1 Fuel Rate',
    56: 'Particulate Trap Active Regeneration Inhibited Status',
    57: 'Particulate Trap Active Regeneration Inhibited Due to Inhibit Switch',
    58: 'Particulate Trap Active Regeneration Inhibited Due to Temporary System Lockout',
    range(59, 150): 'Reserved',
})


# Vehicle Sensors to Data Converter SIDs (MID = 178)
vehicle_sensors_to_data_converter_sids = RangeDict({
    0: 'Reserved',
    1: 'Battery Positive Input',
    2: 'Battery Negative Input',
    3: 'Current Shunt (-) Input',
    4: 'Current Shunt (+) Input',
    5: 'Starter Negative Input',
    6: 'Alternator Negative Input',
    7: 'Transducer +5V Excitation',
    8: 'Starter Positive Input',
    9: 'Starter Solenoid Input',
    10: 'Alternator Positive Input',
    11: 'Alternator Field Input',
    12: 'Fuel Solenoid Positive Input',
    13: 'User Probe Input',
    14: 'Fuel Supply Sender Input',
    15: 'Air Cleaner Delta P Sender Input',
    16: 'Fuel Filter Delta P Sender Input',
    17: 'Oil Filter Inlet Sender Input',
    18: 'Fuel Return Sender Input',
    19: 'Oil Filter Outlet Sender Input',
    20: 'Fuel Vacuum Sender Input',
    21: 'Battery Negative Input Circuit',
    22: 'Battery Positive Input Circuit',
    23: 'Starter Positive Input Circuit',
    24: 'Starter Negative Input Circuit',
    25: 'Starter Solenoid Input Circuit',
    26: 'Alternator Field Input Circuit',
    27: 'Alternator Positive Input Circuit',
    28: 'Alternator Negative Input Circuit',
    29: 'Current Sensor Discharge Circuit',
    30: 'Current Sensor Charge Circuit',
    range(31, 150): 'Reserved',
})


# Refrigerant Management Systems SIDs (MID = 190)
refrigerant_management_systems_sids = RangeDict({
    0: 'Reserved',
    1: 'Refrigerant Charge',
    2: 'Refrigerant Moisture Level',
    3: 'Non-condensable Gas in Refrigerant',
    4: 'Refrigerant Flow Control Solenoid',
    5: 'Low Side Refrigerant Pressure Switch',
    6: 'Compressor Clutch Circuit',
    7: 'Evaporator Thermostat Circuit',
    8: 'Refrigerant Flow',
    9: 'Climate Control Air Filter Differential Pressure Sensor',
    range(10, 150): 'Reserved',
})


# Tractor/Trailer Bridge SIDs (MID = 217, 218)
tractor_trailer_bridge_sids = RangeDict({
    0: 'Reserved',
    1: 'Auxiliary input #1',
    2: 'Auxiliary input #2',
    3: 'Auxiliary input #3',
    4: 'Auxiliary input #4',
    5: 'Auxiliary input #5',
    6: 'Auxiliary input #6',
    7: 'Auxiliary input #7',
    8: 'Auxiliary input #8',
    9: 'Clearance, side marker, identification lamp circuit (Black)',
    10: 'Left turn lamp circuit (Yellow)',
    11: 'Stop lamp circuit (Red)',
    12: 'Right turn lamp circuit (Green)',
    13: 'Tail lamp/license plate lamp circuit (Brown)',
    14: 'Auxiliary lamp circuit (Blue)',
    15: 'Tractor mounted rear axle slider control unit',
    16: 'Trailer mounted rear axle slider control unit',
    range(1, 150): 'Reserved',
})


# Collision Avoidance Systems SIDs (MID = 219)
collision_avoidance_systems_sids = RangeDict({
    0: 'Reserved',
    1: 'Forward Antenna',
    2: 'Antenna Electronics',
    3: 'Brake Input Monitor',
    4: 'Speaker Monitor',
    5: 'Steering Sensor Monitor',
    6: 'Speedometer Monitor',
    7: 'Right Turn Signal Monitor',
    8: 'Left Turn Signal Monitor',
    9: 'Control Display Unit',
    10: 'Right Side Sensor',
    11: 'Left Side Sensor',
    12: 'Rear Sensor',
    range(13, 150): 'Reserved',
})


# Driveline Retarder SIDs (MID = 222)
driveline_retarder_sids = RangeDict({
    0: 'Reserved',
    1: 'Retarder Enable Solenoid Valve',
    2: 'Retarder Modulation Solenoid Valve',
    3: 'Retarder Response Solenoid Valve',
    4: 'Retarder Modulation Request Sensor',
    5: 'Retarder Response System Pressure Indicator',
    range(6, 150): 'Reserved',
})


# Safety Restraint System SIDs (MID = 232, 254)
safety_restraint_system_sids = RangeDict({
    0: 'Reserved',
    1: 'Driver Air Bag Ignitor Loop',
    2: 'Passenger Air Bag Ignitor Loop',
    3: 'Left Belt Tensioner Ignitor Loop',
    4: 'Right Belt Tensioner Ignitor Loop',
    5: 'Safety Restraint System (SRS) Lamp—directly controlled by the ECU',
    6: 'Automotive Seat Occupancy Sensor (AOS)—Passenger Side',
    7: 'Side Collision Detector (SDC)—Left',
    8: 'Side Bag Ignitor Loop 1—Left',
    9: 'Side Bag Ignitor Loop 2—Left',
    10: 'Side Collision Detector—Right',
    11: 'Side Bag Ignitor Loop 1—Right',
    12: 'Side Bag Ignitor Loop 2—Right',
    13: 'Rollover Sensor',
    14: 'Driver Air Bag Stage 2 Igniter Loop',
    15: 'Passenger Air Bag Stage 2 Igniter Loop',
    range(16, 150): 'Reserved',
})


# Forward Road Image Processor SIDs (MID = 248)
forward_road_image_processor_sids = RangeDict({
    0: 'Reserved',
    1: 'Forward View Imager System',
    range(2, 150): 'Reserved',
})


# Brake Stroke Alert Monitor, Tractor SIDs (MID = 253)
brake_stroke_alert_monitor_tractor_sids = RangeDict({
    0: 'Reserved',
    1: 'Tractor Brake Stroke Axle 1 Left',
    2: 'Tractor Brake Stroke, Axle 1 Right',
    3: 'Tractor Brake Stroke, Axle 2 Left',
    4: 'Tractor Brake Stroke, Axle 2 Right',
    5: 'Tractor Brake Stroke, Axle 3 Left',
    6: 'Tractor Brake Stroke, Axle 3 Right',
    7: 'Tractor Brake Stroke, Axle 4 Left',
    8: 'Tractor Brake Stroke, Axle 4 Right',
    9: 'Tractor Brake Stroke Alert Monitor',
    10: 'Trailer #1 Brake Stroke, Axle 1 Left',
    11: 'Trailer #1 Brake Stroke, Axle 1 Right',
    12: 'Trailer #1 Brake Stroke, Axle 2 Left',
    13: 'Trailer #1 Brake Stroke, Axle 2 Right',
    14: 'Trailer #1 Brake Stroke, Axle 3 Left',
    15: 'Trailer #1 Brake Stroke, Axle 3 Right',
    16: 'Trailer #1 Brake Stroke, Axle 4 Left',
    17: 'Trailer #1 Brake Stroke, Axle 4 Right',
    18: 'Trailer #1 Brake Stroke, Alert Monitor',
    19: 'Trailer #2 Brake Stroke, Axle 1 Left',
    20: 'Trailer #2 Brake Stroke, Axle 1 Right',
    21: 'Trailer #2 Brake Stroke, Axle 2 Left',
    22: 'Trailer #2 Brake Stroke, Axle 2 Right',
    23: 'Trailer #2 Brake Stroke, Axle 3 Left',
    24: 'Trailer #2 Brake Stroke, Axle 3 Right',
    25: 'Trailer #2 Brake Stroke, Axle 4 Left',
    26: 'Trailer #2 Brake Stroke Axle 4 Right',
    27: 'Trailer #2 Brake Stroke Alert Monitor',
    28: 'Trailer #3 Brake Stroke, Axle 1 Left',
    29: 'Trailer #3 Brake Stroke, Axle 1 Right',
    30: 'Trailer #3 Brake Stroke, Axle 2 Left',
    31: 'Trailer #3 Brake Stroke, Axle 2 Right',
    32: 'Trailer #3 Brake Stroke, Axle 3 Left',
    33: 'Trailer #3 Brake Stroke, Axle 3 Right',
    34: 'Trailer #3 Brake Stroke, Axle 4 Left',
    35: 'Trailer #3 Brake Stroke Axle 4 Right',
    36: 'Trailer #3 Brake Stroke Alert Monitor',
    37: 'Trailer Brake Stroke, Axle 1 Left',
    38: 'Trailer Brake Stroke, Axle 1 Right',
    39: 'Trailer Brake Stroke, Axle 2 Left',
    40: 'Trailer Brake Stroke, Axle 2 Right',
    41: 'Trailer Brake Stroke, Axle 3 Left',
    42: 'Trailer Brake Stroke, Axle 3 Right',
    43: 'Trailer Brake Stroke, Axle 4 Left',
    44: 'Trailer Brake Stroke, Axle 4 Right',
    45: 'Trailer Brake Stroke Alert Monitor',
    range(46, 150): 'Reserved',
})


mid_to_sid_map = {
    128: (engine_sids, common_sids),
    130: (transmission_sids, common_sids),
    136: (brake_sids, common_sids),
    137: (brake_sids, common_sids),
    138: (brake_sids, common_sids),
    139: (brake_sids, common_sids),
    140: (instrument_panel_sids, common_sids),
    142: (vehicle_management_sids, common_sids),
    142: (fuel_system_sids, common_sids),
    146: (cab_climate_control_sids, common_sids),
    150: (suspension_sids, common_sids),
    151: (suspension_sids, common_sids),
    157: (park_brake_controller_sids, common_sids),
    162: (vehicle_navigation_sids, common_sids),
    162: (vehicle_security_sids, common_sids),
    166: (tire_sids, common_sids),
    168: (tire_sids, common_sids),
    169: (tire_sids, common_sids),
    175: (engine_sids, common_sids),
    176: (transmission_sids, common_sids),
    176: (particulate_trap_sids, common_sids),
    178: (vehicle_sensors_to_data_converter_sids, common_sids),
    183: (engine_sids, common_sids),
    184: (engine_sids, common_sids),
    185: (engine_sids, common_sids),
    186: ((engine_sids, tire_sids), common_sids),
    187: (vehicle_management_sids, common_sids),
    188: (vehicle_management_sids, common_sids),
    190: (refrigerant_management_systems_sids, common_sids),
    191: (vehicle_navigation_sids, common_sids),
    200: (cab_climate_control_sids, common_sids),
    217: (tractor_trailer_bridge_sids, common_sids),
    218: (tractor_trailer_bridge_sids, common_sids),
    219: (collision_avoidance_systems_sids, common_sids),
    222: (driveline_retarder_sids, common_sids),
    223: (transmission_sids, common_sids),
    232: (safety_restraint_system_sids, common_sids),
    234: (instrument_panel_sids, common_sids),
    246: (brake_sids, common_sids),
    247: (brake_sids, common_sids),
    248: (forward_road_image_processor_sids, common_sids),
    253: (brake_stroke_alert_monitor_tractor_sids, common_sids),
    254: (safety_restraint_system_sids, common_sids),
}


def get_sid_string(mid, sid):
    mid_value = mids.get_mid_value(mid)
    sid_table = mid_to_sid_map.get(mid_value, (common_sids,))

    for table in sid_table:
        try:
            return table[sid]
        except KeyError:
            pass
    return f'Unknown SID {sid} for MID {mid_value}'


__all__ = [
    'get_sid_string',
]
