from utils import RangeDict


_pids = RangeDict({
    0: 'Request Parameter',
    range(1, 3): 'Reserved',
    4: 'Dynamic for J2497 Gateway',
    range(5, 6): 'Reserved',
    7: 'Axle #2 Lift Air Pressure',
    8: 'Brake System Air Pressure Low Warning Switch Status',
    9: 'Axle Lift Status',
    10: 'Axle Slider Status',
    11: 'Cargo Securement',
    12: 'Brake Stroke Status',
    13: 'Entry Assist Position/Deployment',
    14: 'Entry Assist Motor Current',
    15: 'Fuel Supply Pump Inlet Pressure',
    16: 'Suction Side Fuel Filter Differential Pressure',
    17: 'Engine Oil Level Remote Reservoir',
    18: 'Extended Range Fuel Pressure',
    19: 'Extended Range Engine Oil Pressure',
    20: 'Extended Range Engine Coolant Pressure',
    21: 'Engine ECU Temperature',
    22: 'Extended Engine Crankcase Blow-by Pressure',
    23: 'Generator Oil Pressure',
    24: 'Generator Coolant Temperature',
    25: 'Air Conditioner System Status #2',
    26: 'Estimated Percent Fan Speed',
    27: 'Percent Exhaust Gas Recirculation Valve #1 Position',
    28: 'Percent Accelerator Position #3',
    29: 'Percent Accelerator Position #2',
    30: 'Crankcase Blow-by Pressure',
    31: 'Transmission Range Position',
    32: 'Transmission Splitter Position',
    33: 'Clutch Cylinder Position',
    34: 'Clutch Cylinder Actuator Status',
    35: 'Shift Finger Actuator Status #2',
    36: 'Clutch Plates Wear Condition',
    37: 'Transmission Tank Air Pressure',
    38: 'Second Fuel Level (Right Side)',
    39: 'Tire Pressure Check Interval',
    40: 'Engine Retarder Switches Status',
    41: 'Cruise Control Switches Status',
    42: 'Pressure Switch Status',
    43: 'Ignition Switch Status',
    44: 'Attention/Warning Indicator Lamps Status',
    45: 'Inlet Air Heater Status',
    46: 'Vehicle Wet Tank Pressure',
    47: 'Retarder Status',
    48: 'Extended Range Barometric Pressure',
    49: 'ABS Control Status',
    50: 'Air Conditioner System Clutch Status/Command #1',
    51: 'Throttle Position',
    52: 'Engine Intercooler Temperature',
    53: 'Transmission Synchronizer Clutch Value',
    54: 'Transmission Synchronizer Brake Value',
    55: 'Shift Finger Positional Status',
    56: 'Transmission Range Switch Status',
    57: 'Transmission Actuator Status #2',
    58: 'Shift Finger Actuator Status',
    59: 'Shift Finger Gear Position',
    60: 'Shift Finger Rail Position',
    61: 'Parking Brake Actuator Status',
    62: 'Retarder Inhibit Status',
    63: 'Transmission Actuator Status #1',
    64: 'Direction Switch Status',
    65: 'Service Brake Switch Status',
    66: 'Vehicle Enabling Component Status',
    67: 'Shift Request Switch Status',
    68: 'Torque Limiting Factor',
    69: 'Two Speed Axle Switch Status',
    70: 'Parking Brake Switch Status',
    71: 'Idle Shutdown Timer Status',
    72: 'Blower Bypass Value Position',
    73: 'Auxiliary Water Pump Pressure',
    74: 'Maximum Road Speed Limit',
    75: 'Steering Axle Temperature',
    76: 'Axle #1 Lift Air Pressure',
    77: 'Forward Rear Drive Axle Temperature',
    78: 'Rear Rear-Drive Axle Temperature',
    79: 'Road Surface Temperature',
    80: 'Washer Fluid Level',
    81: 'Particulate Trap Inlet Pressure',
    82: 'Air Start Pressure',
    83: 'Road Speed Limit Status',
    84: 'Road Speed',
    85: 'Cruise Control Status',
    86: 'Cruise Control Set Speed',
    87: 'Cruise Control High-Set Limit Speed',
    88: 'Cruise Control Low-Set Limit Speed',
    89: 'Power Takeoff Status',
    90: 'PTO Oil Temperature',
    91: 'Percent Accelerator Pedal Position',
    92: 'Percent Engine Load',
    93: 'Output Torque',
    94: 'Fuel Delivery Pressure',
    95: 'Fuel Filter Differential Pressure',
    96: 'Fuel Level',
    97: 'Water in Fuel Indicator',
    98: 'Engine Oil Level',
    99: 'Engine Oil Filter Differential Pressure',
    100: 'Engine Oil Pressure',
    101: 'Crankcase Pressure',
    102: 'Boost Pressure',
    103: 'Turbocharger #1 Speed',
    104: 'Turbo Oil Pressure',
    105: 'Intake Manifold Temperature',
    106: 'Air Inlet Pressure',
    107: 'Air Filter Differential Pressure',
    108: 'Barometric Pressure',
    109: 'Coolant Pressure',
    110: 'Engine Coolant Temperature',
    111: 'Coolant Level',
    112: 'Coolant Filter Differential Pressure',
    113: 'Governor Droop',
    114: 'Net Battery Current',
    115: 'Alternator Current',
    116: 'Brake Application Pressure',
    117: 'Brake Primary Pressure',
    118: 'Brake Secondary Pressure',
    119: 'Hydraulic Retarder Pressure',
    120: 'Hydraulic Retarder Oil Temperature',
    121: 'Engine Retarder Status',
    122: 'Engine Retarder Percent',
    123: 'Clutch Pressure',
    124: 'Transmission Oil Level',
    125: 'Transmission Oil Level High/Low',
    126: 'Transmission Filter Differential Pressure',
    127: 'Transmission Oil Pressure',
    128: 'Component-specific request',
    129: 'Injector Metering Rail #2 Pressure',
    130: 'Power Specific Fuel Economy',
    131: 'Exhaust Back Pressure',
    132: 'Mass Air Flow',
    133: 'Average Fuel Rate',
    134: 'Wheel Speed Sensor Status',
    135: 'Extended Range Fuel Delivery Pressure (Absolute)',
    136: 'Auxiliary Vacuum Pressure Reading',
    137: 'Auxiliary Gage Pressure Reading #1',
    138: 'Auxiliary Absolute Pressure Reading',
    139: 'Tire Pressure Control System Channel Functional Mode',
    140: 'Tire Pressure Control System Solenoid Status',
    141: 'Trailer #1, Tag #1, or Push Channel #1 Tire Pressure Target',
    142: 'Drive Channel Tire Pressure Target',
    143: 'Steer Channel Tire Pressure Target',
    144: 'Trailer #1, Tag #1, or Push Channel #1 Tire Pressure',
    145: 'Drive Channel Tire Pressure',
    146: 'Steer Channel Tire Pressure',
    147: 'Average Fuel Economy (Natural Gas)',
    148: 'Instantaneous Fuel Economy (Natural Gas)',
    149: 'Fuel Mass Flow Rate (Natural Gas)',
    150: 'PTO Engagement Control Status',
    151: 'ATC Control Status',
    152: 'Number of ECU Resets',
    153: 'Crankcase Pressure',
    154: 'Auxiliary Input and Output Status #2',
    155: 'Auxiliary Input and Output Status #1',
    156: 'Injector Timing Rail Pressure',
    157: 'Injector Metering Rail Pressure',
    158: 'Battery Potential (Voltage)—Switched',
    159: 'Gas Supply Pressure',
    160: 'Main Shaft Speed',
    161: 'Input Shaft Speed',
    162: 'Transmission Range Selected',
    163: 'Transmission Range Attained',
    164: 'Injection Control Pressure',
    165: 'Compass Bearing',
    166: 'Rated Engine Power',
    167: 'Alternator Potential (Voltage)',
    168: 'Battery Potential (Voltage)',
    169: 'Cargo Ambient Temperature',
    170: 'Cab Interior Temperature',
    171: 'Ambient Air Temperature',
    172: 'Air Inlet Temperature',
    173: 'Exhaust Gas Temperature',
    174: 'Fuel Temperature',
    175: 'Engine Oil Temperature',
    176: 'Turbo Oil Temperature',
    177: 'Transmission #1 Oil Temperature',
    178: 'Front Axle Weight',
    179: 'Rear Axle Weight',
    180: 'Trailer Weight',
    181: 'Cargo Weight',
    182: 'Trip Fuel',
    183: 'Fuel Rate (Instantaneous)',
    184: 'Instantaneous Fuel Economy',
    185: 'Average Fuel Economy',
    186: 'Power Takeoff Speed',
    187: 'Power Takeoff Set Speed',
    188: 'Idle Engine Speed',
    189: 'Rated Engine Speed',
    190: 'Engine Speed',
    191: 'Transmission Output Shaft Speed',
    192: 'Multisection Parameter',
    193: 'Transmitter System Diagnostic Table',
    194: 'Transmitter System Diagnostic Code and Occurrence Count Table',
    195: 'Diagnostic Data Request/Clear Count',
    196: 'Diagnostic Data/Count Clear Response',
    197: 'Connection Management',
    198: 'Connection Mode Data Transfer',
    199: 'Traction Control Disable State',
    range(200, 202): 'Reserved',
    203: 'Particulate Trap Gas Outlet Temperature',
    204: 'Data Transfer Marker',
    205: 'Time Point Encounter',
    206: 'Agency Identification',
    207: 'Cashbox Information',
    208: 'Total Refrigerant Compressor Hours',
    209: 'ABS Control Status, Trailer',
    210: 'Tire Temperature (By Sequence Number)',
    211: 'Tire Pressure (By Sequence Number)',
    212: 'Tire Pressure Target (By Sequence Number)',
    213: 'Wheel End Assembly Vibration Level',
    214: 'Vehicle Wheel Speeds',
    215: 'Brake Temperature',
    216: 'Wheel Bearing Temperature',
    217: 'Fuel Tank/Nozzle Identification',
    218: 'State Line Crossing',
    219: 'Current State and Country',
    220: 'Engine Torque History',
    221: 'Anti-theft Request',
    222: 'Anti-theft Status',
    223: 'Auxiliary A/D Counts',
    224: 'Immobilizer Security Code',
    225: 'Text Message Acknowledged',
    226: 'Text Message to Display',
    227: 'Text Message Display Type',
    228: 'Speed Sensor Calibration',
    229: 'Total Fuel Used (Natural Gas)',
    230: 'Total Idle Fuel Used (Natural Gas)',
    231: 'Trip Fuel (Natural Gas)',
    232: 'DGPS Differential Correction',
    233: 'Unit Number (Power Unit)',
    234: 'Software Identification',
    235: 'Total Idle Hours',
    236: 'Total Idle Fuel Used',
    237: 'Vehicle Identification Number',
    238: 'Velocity Vector',
    239: 'Vehicle Position',
    240: 'Change Reference Number',
    241: 'Tire Pressure by Position',
    242: 'Tire Temperature by Position',
    243: 'Component Identification',
    244: 'Trip Distance',
    245: 'Total Vehicle Distance',
    246: 'Total Vehicle Hours',
    247: 'Total Engine Hours',
    248: 'Total PTO Hours',
    249: 'Total Engine Revolutions',
    250: 'Total Fuel Used',
    251: 'Clock',
    252: 'Date',
    253: 'Elapsed Time',
    254: 'Data Link Escape',
    256: 'Request Parameter',
    257: 'Cold Restart of Specific Component',
    258: 'Warm Restart of Specific Component',
    259: 'Component Restart Response',
    range(260, 340): 'Reserved',
    341: 'Engine Shutdown Override Switch',
    342: 'Transportation Segment Identifier',
    343: 'Engine Coolant Pump Differential Pressure',
    344: 'Driver Logon Status',
    345: 'Suspension Control Status #1',
    346: 'Suspension Control Status #2',
    347: 'Farebox Probe Type',
    348: 'Cargo Refrigeration System Operating Mode, Zone #1',
    349: 'Cargo Refrigeration System Operating Mode, Zone #2',
    350: 'Cargo Refrigeration System Operating Mode, Zone #3',
    351: 'Turbocharger Compressor Inlet Temperature',
    352: 'Turbocharger #2 Speed',
    353: 'Fuel Leakage Status',
    354: 'Relative Humidity',
    355: 'Engine Oil Life',
    356: 'Fifth Wheel Coupling Status',
    357: 'Ride Adjustment Pressure',
    358: 'Air Suspension #2 Pressure',
    359: 'Air Suspension #1 Pressure',
    360: 'Axle #4 Lift Air Pressure',
    361: 'Axle #3 Lift Air Pressure',
    362: 'Percent Exhaust Gas Recirculation Valve #2 Position',
    363: 'Hydraulic Retarder Control Air Pressure',
    364: 'HVAC Unit Discharge Temperature',
    365: 'Weighing System Status Command',
    366: 'Engine Oil Level High/Low',
    367: 'Lane Tracking System Status',
    368: 'Lane Departure Indication',
    369: 'Distance to Rear Object (Reverse)',
    370: 'Trailer Pneumatic Brake Control Line Pressure',
    371: 'Trailer Pneumatic Supply Line Pressure',
    372: 'Remote Accelerator',
    373: 'Center Rear Drive Axle Temperature',
    374: 'Alternator AC Voltage',
    375: 'Fuel Return Pressure',
    376: 'Fuel Pump Inlet Vacuum',
    377: 'Compression Unbalance',
    378: 'Fare Collection Unit Status',
    379: 'Door Status',
    380: 'Articulation Angle',
    381: 'Vehicle Use Status',
    382: 'Transit Silent Alarm Status',
    383: 'Vehicle Acceleration',
    384: 'Component-specific request',
    385: 'Intake Valve Actuation System Oil Pressure',
    386: 'Evaporator Coil Temperature, Zone #1',
    387: 'Evaporator Coil Temperature, Zone #2',
    388: 'Evaporator Coil Temperature, Zone #3',
    389: 'Cargo Temperature Setpoint, Zone #1',
    390: 'Cargo Temperature Setpoint, Zone #2',
    391: 'Cargo Temperature Setpoint, Zone #3',
    392: 'Evaporator Supply (Discharge) Air Temperature #2, Zone #1',
    393: 'Evaporator Supply (Discharge) Air Temperature #2, Zone #2',
    394: 'Evaporator Supply (Discharge) Air Temperature #2, Zone #3',
    395: 'Evaporator Supply (Discharge) Air Temperature #1, Zone #1',
    396: 'Evaporator Supply (Discharge) Air Temperature #1, Zone #2',
    397: 'Evaporator Supply (Discharge) Air Temperature #1, Zone #3',
    398: 'Evaporator Return Air Temperature #2, Zone #1',
    399: 'Evaporator Return Air Temperature #2, Zone #2',
    400: 'Evaporator Return Air Temperature #2, Zone #3',
    401: 'Evaporator Return Air Temperature #1, Zone #1',
    402: 'Evaporator Return Air Temperature #1, Zone #2',
    403: 'Evaporator Return Air Temperature #1, Zone #3',
    404: 'Turbocharger Compressor Outlet Temperature',
    405: 'Safety Restraint System Trigger Status',
    406: 'HVAC Blower Motor Speed',
    407: 'Axle Group Full Weight Calibration',
    408: 'Axle Group Empty Weight Calibration',
    409: 'Axle Group Weight',
    410: 'Extended Range Road Surface Temperature',
    411: 'Recirculated Engine Exhaust Gas Differential Pressure',
    412: 'Recirculated Engine Exhaust Gas Temperature',
    413: 'Net Vehicle Weight Change',
    414: 'Air Conditioner Refrigerant Low Side Pressure',
    415: 'Air Conditioner Refrigerant High Side Pressure',
    416: 'Evaporator Temperature',
    417: 'Gross Vehicle Weight',
    418: 'Transmission # 2 Oil Temperature',
    419: 'Starter Circuit Resistance',
    420: 'Starter Current (Average)',
    421: 'Alternator/Generator Negative Cable Voltage',
    422: 'Auxiliary Current',
    423: 'Extended Range Net Battery Current',
    424: 'DC Voltage',
    425: 'Auxiliary Frequency',
    426: 'Alternator/Generator Field Voltage',
    427: 'Battery Resistance Change',
    428: 'Battery Internal Resistance',
    429: 'Starter Current Peak',
    430: 'Starter Solenoid Voltage',
    431: 'Starter Negative Cable Voltage',
    432: 'Starter Motor Voltage',
    433: 'Fuel Shutoff Solenoid Voltage',
    434: 'AC Voltage',
    435: 'Cargo Ambient Temperature (By location)',
    436: 'Trip Sudden Decelerations',
    437: 'Trailer #2, Tag #2, or Push Channel #2 Tire Pressure Target',
    438: 'Trailer #2, Tag #2, or Push Channel #2 Tire Pressure',
    439: 'Extended Range Boost Pressure #1',
    440: 'Extended Range Boost Pressure #2',
    441: 'Auxiliary Temperature #1',
    442: 'Auxiliary Temperature #2',
    443: 'Auxiliary Gage Pressure Reading #2',
    444: 'Battery #2 Potential (Voltage)',
    445: 'Cylinder Head Temperature Bank B (right bank)',
    446: 'Cylinder Head Temperature Bank A (left bank)',
    447: 'Passenger Counter',
    448: 'Page 2 Multisection Parameter',
    449: 'Reporting Interval Request',
    450: 'Bridge Filter Control',
    range(451, 497): 'Reserved',
    498: 'Send Keypress Command',
    499: 'Driver Interface Unit (DIU) Object/Form Command',
    500: 'Intersection Preemption Status and Configuration',
    501: 'Signage Message',
    502: 'Fare Collection Unit—Point of Sale',
    503: 'Fare Collection Unit—Service Detail',
    504: 'Annunciator Voice Message',
    505: 'Vehicle Control Head Keyboard Message',
    506: 'Vehicle Control Head Display Message',
    507: 'Driver Identification',
    508: 'Transit Route Identification',
    509: 'Mile Post Identification',
    510: 'Data Link Escape',
    range(512-1021): 'Reserved',
})

def get_pid_name(pid):
    try:
        return _pids.get(pid)
    except KeyError:
        return f'Unknown PID {pid}'
